### ISSUE TITLE
Not enough letters

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#13]
Ukrainian Scrabble version has 104 letters. However, after 70 letters button "Замінити літери" becomes disabled. In total, the game has only about 80 letters.

![123](https://cloud.githubusercontent.com/assets/8424744/15090892/1ab8abfe-1440-11e6-9751-bfef51602d69.png)

**Comment by DeadSith** [comment]
Error is in ChangeBox method. Will be fixed soon.

**Comment by DeadSith** [comment]
@ua2004 
Found no problem with letters disappearing, there should be a bug with button activation. For testing, I will add letter counter on field.

**Comment by DeadSith** [comment]
Fixed

**Comment by ua2004** [comment]
Still not enough letters. There are only 97. Seven more have disappeared.

![bug1](https://cloud.githubusercontent.com/assets/8424744/15256472/5260df4a-194a-11e6-9056-ce87185bf00b.png)
![bug2](https://cloud.githubusercontent.com/assets/8424744/15256478/56cb4d54-194a-11e6-9d17-28bd93dfc268.png)

**Comment by DeadSith** [comment]
@ua2004 
I found the cause of the problem, it is happenning after exiting into main menu and relaunching the game. Will be fixed tomorrow.

**Comment by DeadSith** [comment]
Fixed
