### ISSUE TITLE
"Frozen" letter

### ISSUE THREAD

**Issue by ua2004** [DeadSith/PvP-Scrabble-like-game#3]
Could not put letter "O" on the board. The game said that field was invalid. Afterwards the letter froze over the board and could not be replaced or set to its original place. During the other player's turn the frozen letter disappears, but later comes back again. However, it is possible to put another letters underneath.

![bug1](https://cloud.githubusercontent.com/assets/8424744/14826390/548c2372-0be6-11e6-8830-b01a0a6606b2.png)

**Comment by DeadSith** [comment]
Fixed. Letter is placed outside the field before checking.

**Comment by ua2004** [comment]
The bug still appears:

![image](https://cloud.githubusercontent.com/assets/8424744/15056573/ee223ce8-131a-11e6-9adb-0d7448b0dc9a.png)

Letter "Ч" on the field is frozen. Right click makes it blue but it still cannot be replaced. The original letter "Ч" however is placed back to other letter. Only the copy is frozen.

**Comment by DeadSith** [comment]
@ua2004 
It's Unity bug, found no way to fix it. Try to drag another letter, the stuck one should dissappear. In one of the next commits I will disable renderer of letters, but dragging other letter will still be necessary.

**Comment by ua2004** [comment]
@DeadSith, trying to drag another letter doesn't help. You can play further but the frozen letter is still on the field.

**Comment by DeadSith** [comment]
Did all I could, managed to reproduce bug in some situations. It works now, but I'm not sure there won't be any further errors like these.
